basePath: /
definitions:
  controller.CertRequestSwagger:
    properties:
      cert:
        description: |-
          Cert is the AID certificate to be signed.
          Note: The actual structure of aidgo.AidCert is defined in an external package.
      info:
        description: Info contains additional information for the certificate signing
          process.
    type: object
  controller.HashRequest:
    properties:
      aid:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      hash:
        example: 1234567890abcdef1234567890abcdef
        type: string
    type: object
host: 127.0.0.1:7001
info:
  contact:
    email: a0970785699@gmail.com
    name: Leon Lin
    url: github.com/leon123858
  description: This is the AID Server API DEMO
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: AID Server API
  version: "0.1"
paths:
  /ac/get/key:
    get:
      consumes:
      - application/json
      description: Retrieve the server's public key
      produces:
      - application/json
      responses:
        "200":
          description: Server public key
          schema:
            type: string
      summary: Get server public key
      tags:
      - certificate
  /ac/sign/cert:
    post:
      consumes:
      - application/json
      description: Send a certificate to be signed by the server
      parameters:
      - description: Certificate request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.CertRequestSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: Signed certificate, ref aidgo.AidCert
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Request server to sign a certificate
      tags:
      - certificate
  /register/cert:
    post:
      consumes:
      - application/json
      description: Save a new certificate hash for a given AID
      parameters:
      - description: Hash request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.HashRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Save certificate hash
      tags:
      - utils
  /verify/hash:
    get:
      consumes:
      - application/json
      description: Retrieve the certificate hash for a given AID
      parameters:
      - description: AID (UUID)
        in: query
        name: aid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Certificate hash
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get certificate hash
      tags:
      - utils
schemes:
- http
- https
swagger: "2.0"
