name: aid-server-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate Swagger Docs
        run: make swag
        working-directory: ./aid-server

      - name: Run Tests
        run: make test
        working-directory: ./aid-server

      - name: Build
        run: make build
        working-directory: ./aid-server

      - name: Use Node.js function test
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: make test-function
        working-directory: ./aid-server
